# Generated by Django 6.0.1 on 2026-01-22 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Health_Conditions', models.TextField(blank=True, null=True)),
                ('Breakfast_time', models.TimeField(blank=True, null=True)),
                ('Lunch_time', models.TimeField(blank=True, null=True)),
                ('Dinner_time', models.TimeField(blank=True, null=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_profile', to=settings.AUTH_USER_MODEL)),
                ('full_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='full_name_profile', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
