# Generated by Django 5.2.11 on 2026-02-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
