# Generated by Django 6.0.1 on 2026-02-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Breakfast_time',
            new_name='breakfast_time',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Dinner_time',
            new_name='dinner_time',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Health_Conditions',
            new_name='health_condition',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Lunch_time',
            new_name='lunch_time',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Wakeup_time',
            new_name='wakeup_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
