# Generated by Django 6.0.1 on 2026-02-02 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('users', '0007_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
