# Generated by Django 6.0.1 on 2026-02-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
    ]
