# Generated by Django 6.0.1 on 2026-02-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatboat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
    ]
