# Generated by Django 6.0.1 on 2026-02-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatboat', '0002_remove_chatmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
