# Generated by Django 5.2.11 on 2026-02-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('image', 'Image')], default='text', max_length=10)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='chat/voice/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='chat/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
