# Generated by Django 6.0.1 on 2026-02-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_time',
            name='time',
            field=models.TimeField(),
        ),
    ]
