# Generated by Django 5.2.11 on 2026-02-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
