# Generated by Django 6.0.1 on 2026-02-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_pharmacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='preceptions_image',
            new_name='prescription_image',
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='draft', max_length=20),
        ),
    ]
