# Generated by Django 6.0.1 on 2026-02-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_alter_medicine_time_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
