# Generated by Django 6.0.1 on 2026-02-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_alter_pharmacy_options_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='after_meal',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='before_meal',
        ),
        migrations.AddField(
            model_name='medicine',
            name='after_meal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='before_meal',
            field=models.BooleanField(default=False),
        ),
    ]
