# Generated by Django 5.2.11 on 2026-02-24 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_adminnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminnotification',
            name='is_read',
        ),
    ]
