# Generated by Django 6.0.1 on 2026-02-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_alter_prescription_prescription_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Prescription',
            new_name='prescription',
        ),
    ]
