# Generated by Django 6.0.1 on 2026-02-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_rename_prescription_patient_prescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={},
        ),
    ]
