# Generated by Django 5.2.11 on 2026-02-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_alter_pharmacy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='health_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
