# Generated by Django 6.0.1 on 2026-02-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_medicine_created_at_medicine_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('before_meal', models.BooleanField(default=False)),
                ('after_meal', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='after_meal',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='before_meal',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='how_many_time',
        ),
        migrations.AddField(
            model_name='medicine',
            name='afternoon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afternoon_time', to='prescriptions.medicine_time'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='evening',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evening_time', to='prescriptions.medicine_time'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='morning',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morning_time', to='prescriptions.medicine_time'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='night',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='night_time', to='prescriptions.medicine_time'),
        ),
    ]
