# Generated by Django 6.0.1 on 2026-02-08 04:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0007_medicine_time_remove_medicine_after_meal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_time',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
