# Generated by Django 6.0.1 on 2026-02-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Hospital',
            new_name='hospital_name',
        ),
    ]
