# Generated by Django 6.0.1 on 2026-02-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_hospital_doctor_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=100),
        ),
    ]
