# Generated by Django 6.0.1 on 2026-02-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
