# Generated by Django 6.0.1 on 2026-02-04 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_doctor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='doctors.doctor')),
            ],
        ),
        migrations.DeleteModel(
            name='doctor_note',
        ),
    ]
